### ISSUE TITLE
Pylimbmc compilation error on deploy

### ISSUE THREAD

**Issue by chrisclark** [heroku/heroku-buildpack-python#164]
This appears to have introduced by https://github.com/heroku/heroku-buildpack-python/commit/16a07abd516446c09127c352c560eb9cc086f9fb#diff-d41d8cd98f00b204e9800998ecf8427e

Our team has also filed this ticket with Heroku directly (#128272). Submitting here as well so others experiencing the issue have visibility.

We are still able to deploy to production because the pip requirement is already satisfied in that environment, but that is not the case on our staging environment so we are being blocked from deploying (as well as blocked from spinning up any other environments).

When deploying we receive:

```
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_ZLIB -I/app/.heroku/python/include/python2.7 -c src/pylibmcmodule.c -o build/temp.linux-x86_64-2.7/src/pylibmcmodule.o -fno-strict-aliasing
   In file included from src/_pylibmcmodule.c:34:0:

   src/_pylibmcmodule.h:42:36: fatal error: libmemcached/memcached.h: No such file or directory

    #include <libmemcached/memcached.h>

                                       ^

   compilation terminated.

   error: command 'gcc' failed with exit status 1

   ----------------------------------------
   Cleaning up...
   Command /app/.heroku/python/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_u18064/pylibmc/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-0g0T4V-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_u18064/pylibmc
   Storing debug log for failure in /app/.pip/pip.log
! Push rejected, failed to compile Multipack app
To git@heroku.com:protopantry.git
! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@heroku.com:protopantry.git'
```
